vuelos_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      # Al ejecutar dbt DESDE la carpeta dbt_flights, 
      # '../' sube a la raíz donde está tu archivo .duckdb
      path: '../flights_history.duckdb'
      extensions:
        - httpfs
        - parquet
      threads: 1